In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
penguins = sns.load_dataset("penguins")
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

### 1번 문제 
- 성별 × 종(species)에 따른 평균 체중 비교
- body_mass_g 컬럼을 이용해, 펭귄의 몸무게를 kg 단위로 변환한 body_mass_kg 파생변수를 만들어라. (공식: body_mass_kg = body_mass_g / 1000)
- 성별(sex) × 종(species) 조합별 평균 body_mass_kg를 계산하라.
- 어떤 종 × 성별 조합이 가장 무거운지를 찾고, 그 이유를
- bill_length_mm(부리 길이)
- flipper_length_mm(날개 길이)같은 다른 변수와 연결해서 데이터적으로 해석해보라.

In [59]:
penguins["body_mass_kg"] = penguins["body_mass_g"] / 1000

#성별 * 종 조합별 평균 몸무게(kg)
kgs = penguins.groupby(["sex", "species"])[["body_mass_kg"]].mean().round(3)

#몸무게가 무거운 순으로 Top3 뽑기
kgs.sort_values("body_mass_kg", ascending = False).head(3)

                body_mass_kg
sex    species
Male   Gentoo          5.485
Female Gentoo          4.680
Male   Adelie          4.043

In [60]:
#몸무게가 최댓값인 하나만 표출
kgs[kgs["body_mass_kg"] == kgs["body_mass_kg"].max()]

              body_mass_kg
sex  species
Male Gentoo          5.485

In [ ]:
#종별 몸무게(kg)에 따른 부리 길이와 날개 길이의 경향성 - Gentoo가 몸무게가 큰 편(그 중에서도  Male > Female), 그만큼 부리도 날개도 큼직큼직해서 상위권을 차지한다.
#그 다음 등장하는 건 아델리
addkgs = penguins.groupby(["sex", "species", "body_mass_kg"])[["bill_length_mm", "flipper_length_mm"]].mean().round(3)
addkgs.sort_values("body_mass_kg", ascending = False).head(45)

                               bill_length_mm  flipper_length_mm
sex    species   body_mass_kg
Male   Gentoo    6.300                 49.200            221.000
                 6.050                 59.600            230.000
                 6.000                 49.950            221.000
                 5.950                 47.500            226.000
                 5.850                 50.933            220.000
                 5.800                 49.050            229.500
                 5.750                 50.400            222.000
                 5.700                 49.920            224.200
                 5.650                 50.533            223.333
                 5.600                 53.350            228.000
                 5.550                 50.450            222.500
                 5.500                 49.780            220.200
                 5.450                 52.500            221.000
                 5.400                 49.720            220.200
                 5.350                 49.133            218.000
                 5.300                 47.800            218.500
                 5.250                 47.600            222.000
Female Gentoo    5.200                 45.850            214.500
Male   Gentoo    5.200                 48.750            222.500
Female Gentoo    5.150                 49.100            220.000
Male   Gentoo    5.150                 46.800            215.000
                 5.100                 47.150            218.000
Female Gentoo    5.100                 44.900            213.000
                 5.050                 45.100            207.000
Male   Gentoo    5.050                 45.650            217.500
Female Gentoo    5.000                 46.167            215.333
Male   Gentoo    5.000                 47.333            222.000
Female Gentoo    4.975                 47.200            215.000
                 4.950                 45.050            215.500
Male   Gentoo    4.925                 49.400            216.000
Female Gentoo    4.925                 47.200            214.000
                 4.900                 45.050            217.000
                 4.875                 47.200            217.000
                 4.850                 46.600            214.500
                 4.800                 45.800            210.000
Male   Chinstrap 4.800                 52.000            210.000
       Adelie    4.775                 43.200            197.000
Female Gentoo    4.750                 45.825            213.750
Male   Gentoo    4.750                 49.600            216.000
       Adelie    4.725                 41.000            203.000
Female Gentoo    4.725                 47.400            212.000
Male   Adelie    4.700                 42.900            196.000
Female Gentoo    4.700                 44.040            214.800
Male   Adelie    4.675                 39.200            195.000
                 4.650                 39.800            184.000

In [73]:
#각 펭귄 종별 몸무게(kg)와 부리 길이 비교
penguins.groupby(["species", "body_mass_kg"])[["bill_length_mm"]].mean().round(3)

                      bill_length_mm
species body_mass_kg
Adelie  2.850                 36.450
        2.900                 35.400
        2.925                 37.900
        2.975                 37.500
        3.000                 37.150
...                              ...
Gentoo  5.850                 50.933
        5.950                 47.500
        6.000                 49.950
        6.050                 59.600
        6.300                 49.200

[136 rows x 1 columns]

In [ ]:
#각 펭귄 종별 몸무게(kg)와 날개 길이 비교
penguins.groupby(["species", "body_mass_kg"])[["flipper_length_mm"]].mean().round(3)

                      flipper_length_mm
species body_mass_kg
Adelie  2.850                   182.500
        2.900                   184.333
        2.925                   193.000
        2.975                   179.000
        3.000                   188.500
...                                 ...
Gentoo  5.850                   220.000
        5.950                   226.000
        6.000                   221.000
        6.050                   230.000
        6.300                   221.000

[136 rows x 1 columns]

### 2번 문제 
- flipper 길이 기반 “날개 레벨” 만들기
- flipper_length_mm(날개 길이)를 기준으로 팽귄을 세 구간으로 나누어라.
  - 하위 50% 미만 → "short"
  - 50% ~ 80% 분위수 → "mid"
  - 상위 20% 이상 → "long"
  - 이 기준을 사용해 flipper_level 이라는 파생 변수를 만들어라. (힌트: quantile()과 조건문 또는 pd.qcut() 활용 가능)

- species(종) × island(서식지) × flipper_level 조합별로 평균 body_mass_g를 계산하라.

- 평균 body_mass_g가 가장 높은 조합 TOP 3를 내림차순으로 출력하라.

TOP 1 조합이 왜 무거운지,
해당 종의 특성
해당 island(서식지) 환경
flipper_level(날개 길이)를 바탕으로 데이터적 관점에서 해석해보라.

In [ ]:
penguins["flipper_level"] = pd.qcut(penguins["flipper_length_mm"], q = [0, 0.5, 0.8, 1.0], labels = ["short", "mid", "long"])

#종 * 서식지 * 날개 레벨 조합별로 평균 몸무게(g) 계산
penguins.groupby(["species", "island", "flipper_level"])[["body_mass_g"]].mean().round(3)
##아델리는 날개가 짧은 편이다./신스트랩은 드림에서만 산다./젠투는 비스코에서만 산다. + 날개도 긴 편

C:\Users\user\AppData\Local\Temp\ipykernel_22100\1264842819.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  penguins.groupby(["species", "island", "flipper_level"])[["body_mass_g"]].mean().round(3)

                                   body_mass_g
species   island    flipper_level
Adelie    Biscoe    short             3671.875
                    mid               4087.500
                    long                   NaN
          Dream     short             3639.000
                    mid               4100.000
                    long                   NaN
          Torgersen short             3659.659
                    mid               4000.000
                    long                   NaN
Chinstrap Biscoe    short                  NaN
                    mid                    NaN
                    long                   NaN
          Dream     short             3570.833
                    mid               3995.192
                    long                   NaN
          Torgersen short                  NaN
                    mid                    NaN
                    long                   NaN
Gentoo    Biscoe    short                  NaN
                    mid               4779.911
                    long              5323.507
          Dream     short                  NaN
                    mid                    NaN
                    long                   NaN
          Torgersen short                  NaN
                    mid                    NaN
                    long                   NaN

In [95]:
penguins[["body_mass_g"]].fillna(0.0)
penguins.groupby(["species", "island", "flipper_level"])["body_mass_g"].mean().sort_values(ascending = False).head(3)

C:\Users\user\AppData\Local\Temp\ipykernel_22100\498907140.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  penguins.groupby(["species", "island", "flipper_level"])["body_mass_g"].mean().sort_values(ascending = False).head(3)

species  island  flipper_level
Gentoo   Biscoe  long             5323.507463
                 mid              4779.910714
Adelie   Dream   mid              4100.000000
Name: body_mass_g, dtype: float64

### 3번 문제 
- “일반적으로 무거운 펭귄 그룹” 찾기
- 다음 네 가지 조건을 모두 사용하는 그룹을 만들라:
  - 종(species)
  - 섬(island)
  - 성별(sex)
- 날개 레벨(flipper_level, 2번 문제에서 만든 것) 즉, species × island × sex × flipper_level 조합으로 그룹을 만든다.

- 각 그룹에 대해 body_mass_g의 평균(mean), 분산(var)을 동시에 구하라.

- 평균 몸무게가 크면서, 분산은 낮은 그룹을 “일반적으로 무거운 그룹”이라고 정의
- 이 기준에 따라 TOP 3 그룹을 선정하라. (예: score = mean / (var + 작은 값) 처럼 점수를 만들어도 됨)
- 선택된 TOP 3 그룹의 공통점이 무엇인지 종(species), 성별(sex), flipper_level(날개 길이) 관점에서 해석해보라.

In [105]:
heavy_penguins = penguins.groupby(["species", "island", "sex", "flipper_level"])["body_mass_g"].agg(["mean", "var"])

heavy_penguins.sort_values(by=["mean", "var"], ascending=[False, True]).round(3)

C:\Users\user\AppData\Local\Temp\ipykernel_22100\2764336691.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  heavy_penguins = penguins.groupby(["species", "island", "sex", "flipper_level"])["body_mass_g"].agg(["mean", "var"])

                                              mean         var
species   island    sex    flipper_level
Gentoo    Biscoe    Male   long           5506.500  105785.969
                           mid            5386.364   57045.455
                    Female long           4832.143   47060.440
                           mid            4631.250   80904.797
Adelie    Biscoe    Male   mid            4387.500  227812.500
          Dream     Male   mid            4210.000   46437.500
Chinstrap Dream     Male   mid            4128.947   81476.608
Adelie    Torgersen Male   short          4050.000  157416.667
          Biscoe    Male   short          4016.250  114557.566
          Dream     Male   short          4009.783  118166.996
          Torgersen Male   mid            4000.000  113125.000
          Biscoe    Female mid            3787.500    2812.500
Chinstrap Dream     Male   short          3698.333   93345.238
                    Female mid            3632.143   66190.476
Adelie    Dream     Female mid            3550.000         NaN
Chinstrap Dream     Female short          3500.000   84326.923
Adelie    Torgersen Female short          3395.833   67155.797
          Dream     Female short          3336.538   45011.538
          Biscoe    Female short          3327.500  109993.421
                           long                NaN         NaN
                    Male   long                NaN         NaN
          Dream     Female long                NaN         NaN
                    Male   long                NaN         NaN
          Torgersen Female mid                 NaN         NaN
                           long                NaN         NaN
                    Male   long                NaN         NaN
Chinstrap Biscoe    Female short               NaN         NaN
                           mid                 NaN         NaN
                           long                NaN         NaN
                    Male   short               NaN         NaN
                           mid                 NaN         NaN
                           long                NaN         NaN
          Dream     Female long                NaN         NaN
                    Male   long                NaN         NaN
          Torgersen Female short               NaN         NaN
                           mid                 NaN         NaN
                           long                NaN         NaN
                    Male   short               NaN         NaN
                           mid                 NaN         NaN
                           long                NaN         NaN
Gentoo    Biscoe    Female short               NaN         NaN
                    Male   short               NaN         NaN
          Dream     Female short               NaN         NaN
                           mid                 NaN         NaN
                           long                NaN         NaN
                    Male   short               NaN         NaN
                           mid                 NaN         NaN
                           long                NaN         NaN
          Torgersen Female short               NaN         NaN
                           mid                 NaN         NaN
                           long                NaN         NaN
                    Male   short               NaN         NaN
                           mid                 NaN         NaN
                           long                NaN         NaN